---
permalink: intro-family.html
keywords: introduction, what E-Series is, e-series, SANtricity, CLI, system manager, unified manager
summary: "The NetApp E-Series product family offers storage and application data management services for high-bandwidth applications that need simple, easy to manage, and fast block storage with enterprise-grade reliability."
---

= Intro to the ONTAP family of storage systems
:hardbreaks:
:icons: font
:imagesdir: ./media/

The NetApp ONTAP storage family offers integrated data protection and seamless backup and recovery to the cloud, and is designed for dedicated, high-bandwidth applications that need simple, easy to manage, and fast all-flash storage with enterprise-grade reliability.

== AFF systems Family
ONTAP AFF storage systems use .

ONTAP AFF storage systems include the following platform models.

=== Entry-level systems: AFF C190, AFF A250, FAS2720, FAS2750
Designed to meet the data management needs for mid-size businesses or remote offices of a large enterprise. https://www.netapp.com/pdf.html?item=/media/63961-DS-4174-Entry-level-systems-overview.pdf[Read the AFF Datasheet^].

=== AFF A400
End-to-end NVMe all-flash system that offers extremely low latency at a mid-range price point for enterprise applications, data analytics, and artificial intelligence workloads. https://www.netapp.com/pdf.html?item=/media/7572-ds-3894.pdf[Read the E5700 Datasheet^].

=== AFF A800
Delivers high-end performance, but in a compact form that's especially suited for EDA and
media/entertainment workloads. https://www.netapp.com/pdf.html?item=/media/7573-ds-3805.pdf[Read the Datasheet^].

=== AFF A900
Delivers advanced reliability, availability, and serviceability (RAS) that keep your critical data always available. It also provides all the core data management and data protection capabilities for your enterprise applications https://www.netapp.com/pdf.html?item=/media/7573-ds-3805.pdf[Read the Datasheet^].

== FAS systems

NetApp FAS hybrid flash arrays are simple, smart, trusted storage shared NAS and SAN environments that provide rich data management and easy cloud integration. Powered by ONTAP data management software, they are ideal for back-up and retention, consolidation of general business applications, and distributed content. https://www.netapp.com/pdf.html?item=/media/19763-ds-3829.pdf[Read the FAS Datasheet^].

=== FAS8700
Optimized for high capacity and performance to consolidate multiple business workloads.

=== FAS8300
Next-generation midrange system designed for a wide range of deployments that need a
balance of capacity and performance.

== For more information

* https://docs.netapp.com/us-en/e-series/index.html[E-Series system docs^]
* https://docs.netapp.com/us-en/e-series-santricity/index.html[SANtricity software docs^]
* https://docs.netapp.com/us-en/e-series-cli/index.html[SANtricity CLI docs^]
