---
permalink: intro-family.html
keywords: introduction, what is ONTAP systems, AFF, FAS, ASA, all-flash, ONTAP
summary: "NetApp's ONTAP family of storage systems is designed for enterprise applications that need easy to manage, fast and secure storage with enterprise-grade reliability and continuous data access."
---
= Learn about ONTAP hardware systems
:hardbreaks:
:icons: font
:imagesdir: ./media/

[.lead]
NetApp's ONTAP hardware systems are designed for enterprise applications that need easy to manage, fast and secure storage with enterprise-grade reliability and continuous data access.

NetApp's ONTAP hardware systems are available in all-flash and hybrid flash and HDD-only configurations, giving you the option to choose the storage media mix that best meets your performance, capacity, and cost requirements.

You can cluster different combinations of models to run mixed workloads on the same storage system and build out your environment by adding new generations of storage with the latest technologies.

== All-Flash FAS (AFF) systems

NVMe-based AFF systems are a robust scale-out platform built for virtualized environments and can be deployed as an independent system or a high-performance tier in a NetApp ONTAP configuration.

Supporting a range of workloads, especially VDI and databases that require high performance, low latency and reliability, the all-flash FAS configurations are the ideal choice for business-critical applications.

* https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf[Read the AFF A-Series datasheet^]
* https://www.netapp.com/media/81583-da-4240-aff-c-series.pdf[Read the AFF C-Series datasheet^]

== AFX 
NetApp AFX is an enterprise-grade disaggregated all-flash storage system that delivers all the performance benefits of parallel file systems and niche AI storage solutions, but on an enterprise-grade platform that is simple, secure, and fully integrated. 

* https://www.netapp.com/pdf.html?item=/media/142853-ds-3466-netapp-afx-datasheet.pdf[Read the AFX datasheet^]
* https://docs.netapp.com/us-en/ontap-afx/get-started/ontap-afx-storage.html[Learn more about AFX storage^]

== All-Flash SAN Array (ASA) systems
NetApp All-Flash SAN Array (ASA) delivers a simplified and dedicated SAN experience that provides continuous data availability for enterprise mission critical databases and other SAN workloads via FCP or iSCSI protocol.

.ASA r2 systems
The new NetApp ASA r2 systems (ASA A1K, ASA A70, ASA A90, ASA A20, ASA A30, ASA A50 and C30) deliver a unified hardware and software solution that creates a simplified experience specific to the needs of SAN-only customers.

On an ASA r2 system, ONTAP software and System Manager are streamlined to provide support for essential SAN functionality while removing visibility of features and functions not supported in SAN environments. 

* https://www.netapp.com/data-storage/all-flash-san-storage-array/[Read the ASA datasheet^] 
* Learn more about the link:https://docs.netapp.com/us-en/asa-r2/learn-more/hardware-comparison.html[new ASA r2 systems in comparison to the ASA systems^]
* See the full configuration support and limitations for ASA and ASA r2 systems in https://hwu.netapp.com/[NetApp Hardware Universe^]

== FAS hybrid-flash systems

FAS hybrid-flash systems are a hardware platform created for shared, consolidated SAN and NAS environments that require rich data management and easy cloud connection.

With its highly available hardware, FAS hybrid-flash systems cost-effectively meet workload demands by combining the ideal mix of flash and traditional spinning drives. It is ideal for back-up and retention, consolidation of general business applications, and distributed content.

https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf[Read the FAS datasheet^]


== MetroCluster
ONTAP's hardware storage systems configured with ONTAP's MetroCluster functionality provides a solution that combines array-based clustering with synchronous replication to deliver continuous availability and zero data loss. The MetroCluster configuration immediately duplicates all mission-critical data on a transaction-by-transaction basis, providing uninterrupted access to applications and data.

Unlike standard data replication solutions, MetroCluster works seamlessly with your host environment to provide continuous data availability while eliminating the need to create and maintain complicated failover scripts.

https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf[Learn more about MetroCluster^]

== ONTAP software
ONTAP data management software is the clustered storage software that powers the ONTAP hardware systems. With a global namespace that supports up to 24 hardware nodes of all types, ONTAP software supports unified storage (block and file), enabling significant workload consolidation that you can manage using the ONTAP System Manager GUI.

https://www.netapp.com/pdf.html?item=/media/7413-ds-3231.pdf[Read the ONTAP software datasheet^]

.For more information

* https://docs.netapp.com/us-en/ontap-systems/index.html[ONTAP hardware systems docs^]
* https://docs.netapp.com/us-en/ontap-metrocluster/index.html[MetroCluster docs^]
* https://docs.netapp.com/us-en/ontap/index.html[ONTAP docs^]
