---
settings:
  name: ONTAP Systems Family
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: ONTAP Systems product family documentation
      url: /index.html
product-family:
  search: "clouddocs-e-series_main-prod,clouddocs-e-series-santricity_main-prod,clouddocs-e-series-cli_main-prod"
  sidebarlinks:
      - title: All docs
        tags: tag_storage_management,tag_data_storage,tag_cli,tag_get_started,tag_SANtricity
        class: active
      - title: Get started
        tags: tag_get_started
      - title: System hardware
        tags: tag_storage_hardware
      - title: System upgrade
        tags: tag_storage_upgrade
      - title: Storage management
        tags: tag_storage_management

  tiles:
    - title: "Learn about the ONTAP Systems family"
      icon: ./media/groups_line-1.png
      url: intro-family.html
      summary: "Learn about the ONTAP Systems family of storage systems."
      tags: all, tag_get_started

    - title: "ONTAP Systems (AFF and FAS)"
      icon: ./media/system_line.png
      url: https://docs.netapp.com/us-en/e-series/index.html
      summary: "Use ONTAP AFF and FAS systems to support your application workloads with high performance storage and enterprise-grade reliability across your hybrid cloud."
      tags: all, tag_storage_hardware, tag_storage_management

    - title: "ONTAP Systems Upgrade"
      icon: ./media/api.png
      url: https://docs.netapp.com/us-en/ontap-systems-upgrade/index.html
      summary: "Learn how to upgrade your AFF and FAS storage systems."
      tags: all, tag_storage_hardware, tag_storage_upgrade

    - title: "Cluster and Storage Switches"
      icon: ./media/config_line.png
      url: https://docs.netapp.com/us-en/ontap-systems-switches/index.html
      summary: "Learn how to install, upgrade and maintain your cluster and storage switches."
      tags: all, tag_storage_hardware, tag_storage_upgrade

    - title: "ONTAP MetroCluster"
      icon: ./media/api.png
      url: https://docs.netapp.com/us-en/ontap-systems-upgrade/index.html
      summary: "Use Metrocluster to deliver continuous high availability and disaster recovery for your storage systems by combining array-based clustering with synchronous replication."
      tags: all, tag_storage_management, tag_storage_upgrade

    - title: "ONTAP Software Family"
      icon: ./media/cli_line.png
      url: https://docs.netapp.com/us-en/ontap-family/index.html
      summary: "Use the ONTAP Software family page to find information on how to set up ONTAP, provision storage for clients, and protect and manage your data with System Manager or the CLI."
      tags: all, tag_storage_management
