---
settings:
  name: AFF and FAS Family
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
sidebar:
  entries:
    - title: AFF and FAS documentation
      url: /index.html
product-family:
  search: "clouddocs-ontap-systems_main-prod,clouddocs-ontap-systems-upgrade_main-prod,clouddocs-ontap-systems-switches_main-prod,clouddocs-ontap-metrocluster_main-prod"
  sidebarlinks:
      - title: All
        tags: tag_storage_management,tag_storage_upgrade,tag_storage_hardware,tag_get_started
        class: active
      - title: Get started
        tags: tag_get_started
      - title: System hardware
        tags: tag_storage_hardware
      - title: System upgrade
        tags: tag_storage_upgrade
  #    - title: Storage management
  #      tags: tag_storage_management

  tiles:
    - title: "Learn about AFF and FAS"
      icon: ./media/family.png
      url: intro-family.html
      summary: "Learn about the AFF and FAS family of storage systems."
      tags: all, tag_get_started

    - title: "AFF and FAS install and maintain"
      icon: ./media/icon-onprem.png
      url: https://docs.netapp.com/us-en/ontap-systems/index.html
      summary: "Install and maintain your AFF, FAS, or All SAN Array systems."
      tags: all, tag_storage_hardware

    - title: "AFF and FAS upgrade"
      icon: ./media/upgrade.png
      url: https://docs.netapp.com/us-en/ontap-systems-upgrade/index.html
      summary: "Upgrade your AFF and FAS storage systems."
      tags: all, tag_storage_upgrade

    - title: "Cluster and storage switches"
      icon: ./media/switch.png
      url: https://docs.netapp.com/us-en/ontap-systems-switches/index.html
      summary: "Install, upgrade and maintain your cluster and storage switches."
      tags: all, tag_storage_hardware, tag_storage_upgrade

    - title: "ONTAP MetroCluster"
      icon: ./media/metrocluster.png
      url: https://docs.netapp.com/us-en/ontap-metrocluster/index.html
      summary: "Install and upgrade or expand your MetroCluster configurations and perform disaster recovery."
      tags: all, tag_storage_upgrade

  #  - title: "ONTAP family"
  #    icon: ./media/family.png
#      url: https://docs.netapp.com/us-en/ontap-family/index.html
#      summary: "Use the ONTAP family page to find information on how to set up ONTAP, provision storage for clients, and protect and manage your data with System Manager or the CLI."
#      tags: all, tag_storage_management
