settings:
  name: ONTAP hardware systems
  search: "ontap-systems,ontap-systems-upgrade,ontap-systems-switches,ontap-metrocluster"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: true
sidebar:
  entries:
    - title: ONTAP hardware systems documentation
      url: /index.html
